### ISSUE TITLE
question:is there gonna be support for other platform's 

### ISSUE THREAD

**Issue by gummybear17** [polybiusproxy/PolyEngine#7]
i was trying to build it on my mac but it give's me error so idk if i have to install something to get rid of the error's 
please tell me

**Comment by gummybear17** [comment]
with the mp4 video player

**Comment by polybiusproxy** [comment]
@gummybear17 Hi there! Thanks for your interest in PolyEngine.
At the moment, you can only build for Windows due to the support of MP4 videos.

I don't have a Mac, so I can't make it work in any way.
However it's being worked thanks to @TentaRJ.

Right now, you can build version 2.1 without problems since it doesn't have the MP4 support.

**Comment by gummybear17** [comment]
well i can help you with the mp4 mac just tell me what to do

**Comment by MrClogsworthYT** [comment]
nice

**Comment by polybiusproxy** [comment]
> well i can help you with the mp4 mac just tell me what to do

just get me vlc 2.1.0 mac libs and done

**Comment by gummybear17** [comment]
bet

**Comment by gummybear17** [comment]
I will do it right now

**Comment by gummybear17** [comment]
does it 

> > well i can help you with the mp4 mac just tell me what to do
> 
> just get me vlc 2.1.0 mac libs and done

do I have to get that version of it

**Comment by gummybear17** [comment]
?
